#!/usr/bin/python

import munin
from subprocess import Popen, PIPE
import json
import os

class CephMDS(munin.MuninPlugin):
    title = "MDS Req Count"
    args = "--base 1000"
    category = "Ceph"

    @property
    def fields(self):
        f = [
            ("req", dict(label="req count",
                      info="Requests",
                      type="COUNTER",
                      min="0")),
            ("reply", dict(label="reply count",
                      info="Replys",
                      type="COUNTER",
                      min="0")),
            # ("", dict(label="",
            #           info="s",
            #           type="GAUGE",
            #           min="0")),
            ]
        return f

    def execute(self):
        if "cephmdsasok" not in os.environ:
            return

        cmd = "ceph --admin-daemon " + os.environ["cephmdsasok"] + " perfcounters_dump"
        output = Popen(cmd.split(), stdout=PIPE).communicate()[0]
        obj = json.loads(output)
        mds = obj["mds"]

        res = {}
        def doit(n):
            res[n] = mds[n]
        doit("req")
        doit("reply")
        return res

if __name__ == "__main__":
    CephMDS().run()
