#!/usr/bin/python

import munin
from subprocess import Popen, PIPE
import json
import os

class CephOSD(munin.MuninPlugin):
    title = "OSD Throttle Latency"
    args = "--base 1000"
    category = "Ceph"

    @property
    def fields(self):
        f = [
            ("throttle-filestore_bytes", dict(label="",
                      info="s",
                      type="GAUGE",
                      min="0")),
            ]
        return f

    def execute(self):
        if "cephosdasok" not in os.environ:
            return

        cmd = "ceph --admin-daemon " + os.environ["cephosdasok"] + " perfcounters_dump"
        output = Popen(cmd.split(), stdout=PIPE).communicate()[0]
        obj = json.loads(output)
        osd = obj["osd"]

        res = {}
        def doit(n):
            latency = osd[n]
            if latency["avgcount"] == 0:
                res[n] = float('nan')
            else:
                res[n] = latency["sum"] / latency["avgcount"]
        doit("op_latency")
        doit("op_r_latency")
        doit("op_rw_latency")
        doit("op_w_latency")
        return res

if __name__ == "__main__":
    CephOSD().run()
