#!/usr/bin/python

import sys
import os
sys.path.append(os.path.dirname(os.path.realpath(__file__))+"/munin-1.4-py2-none-any.whl")
import munin
from subprocess import Popen, PIPE
import json
import re


class CephOSDFilestoreBytes(munin.MuninPlugin):
    title = "OSD Filestore Bytes"
    args = "--base 1024"
    category = "Ceph"

    @property
    def fields(self):
        f = [("journal_queue_bytes", dict(label="journal queue bytes",
                                          info='Journal Queue Bytes',
                                          type='GAUGE',
                                          min="0")),
             ("bytes", dict(label="bytes",
                            info="Bytes",
                            type="COUNTER",
                            min="0")),
             ("journal_bytes", dict(label="journal bytes",
                                    info="Journal Bytes",
                                    type="COUNTER",
                                    min="0")),
             ("op_queue_bytes", dict(label="op queue bytes",
                                     info="Op Queue Bytes",
                                     type="GAUGE",
                                     min="0")),
             ]
        return f

    def execute(self):
        if "cephosdasok" not in os.environ:
            return
        plugin_name = list(os.path.split(sys.argv[0]))[1]
        m = re.search("ceph_osd_(\d+)_.*", plugin_name )
        osdnumber = m.group(1)
        socketfile = os.environ["cephosdasok"]+osdnumber+".asok"

        cmd = "ceph --admin-daemon " + socketfile + " perfcounters_dump"
        output = Popen(cmd.split(), stdout=PIPE).communicate()[0]
        obj = json.loads(output)
        filestore = obj["filestore"]

        res = {}
        res["journal_queue_bytes"] = filestore["journal_queue_bytes"]
        res["journal_bytes"] = filestore["journal_bytes"]
        res["bytes"] = filestore["bytes"]
        res["op_queue_bytes"] = filestore["op_queue_bytes"]
        return res

if __name__ == "__main__":
    CephOSDFilestoreBytes().run()
